In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn
print(np.__version__)

1.16.4


# Numpy basics

## Creating arrays

In [19]:
multidata = np.array(range(1,4))
multidata

array([1, 2, 3])

### Create array with list

In [11]:
multidata = np.array([range(i,i+3) for i in [1,2,3]])
print(multidata)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


### Create array with random methods

In [14]:
np.random.random((3,3))

array([[0.41684425, 0.8486819 , 0.94624226],
       [0.54908521, 0.91299731, 0.23443871],
       [0.76859629, 0.94212325, 0.51640369]])

In [15]:
np.random.normal(0,1,(3,3))

array([[-1.327304  ,  0.56943398, -0.43729527],
       [-0.54546093, -0.94115649,  0.65815333],
       [ 0.20146329,  0.56751122, -1.83885783]])

In [41]:
np.random.seed(0)
np.random.randint(0,10, 6)

array([5, 0, 3, 3, 7, 9])

In [42]:
np.random.randint(0,10,(3,3))

array([[3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [36]:
np.zeros((2,3), dtype="int") # "np.int16"

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [52]:
print(np.empty(5))
x= np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)

[ 0. 10. 20. 30. 40.]


array([ 0., 10., 20., 30., 40.])

## Numpy array properties

In [61]:
my_grid = np.arange(16).reshape((4,4))
my_grid 
print(my_grid.shape)
print(my_grid.ndim)
print(my_grid.size)
print(my_grid.dtype)

(4, 4)
2
16
int64


In [64]:
my_grid[0][1:]

array([99,  2,  3])

In [63]:
my_grid[0][1] = 99
my_grid 

array([[ 0, 99,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
sub_arrays = my_grid[:2, :3] # views when using slice but in python slice will be copies
sub_arrays

array([[ 0, 99,  2],
       [ 4,  5,  6]])

In [74]:
sub_arrays[0][1] = 999 # because of view, the original will be influenced
my_grid

array([[  0, 999,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [78]:
sub_arrays_copy = my_grid[:2, :3].copy()
sub_arrays_copy[0][1] = 9999
my_grid

array([[  0, 999,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [67]:
sub_arrays2 = my_grid[:3, ::2]
sub_arrays2


array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [70]:
first_row = my_grid[0]
first_row

array([ 0, 99,  2,  3])

In [72]:
first_column = my_grid[:,0]
first_column

array([ 0,  4,  8, 12])

## Reshaping and concatenating

In [79]:
x= np.arange(7,10)
y= np.arange(1,4)
np.concatenate((x,y))

array([7, 8, 9, 1, 2, 3])

In [80]:
x= np.array([[1,2],
              [3,4]])
y= np.array([[9,10]])
j = np.concatenate((x,y),axis = 0)
k = np.concatenate((x,y.T),axis = 1)
l = np.concatenate((x,y),axis = None)
print(j)
print(k)
print(l)

[[ 1  2]
 [ 3  4]
 [ 9 10]]
[[ 1  2  9]
 [ 3  4 10]]
[ 1  2  3  4  9 10]
