In [1]:
import numpy as np
import tensorflow as tf


In [24]:
coefficients = np.array([[1.],[-20.],[100]])

w = tf.Variable(0,dtype=tf.float32)

# placeholder means a variable that you can assign later
# get training data into the cost function
x = tf.placeholder(tf.float32,[3,1]) 

#cost =tf.add(tf.add(w**2,tf.multiply(-10.,w)),25)
cost = x[0][0]*w**2 - x[1][0]*w + x[2][0]

train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

init=tf.global_variables_initializer()
session = tf.Session()
session.run(init)
print(session.run(w))

# 直接用with也可以，紧接training
# with tf.Session() as session:
#     session.run(init)
#     print(session.run(w))
#     session.run(train,feed_dict={x:coefficients})
#     print(session.run(w))
#     for i in range(1000):
#         session.run(train,feed_dict={x:coefficients})
#     print(session.run(w))

0.0


In [25]:
session.run(train,feed_dict={x:coefficients})
print(session.run(w))

-0.19999999


In [26]:
for i in range(1000):
    session.run(train,feed_dict={x:coefficients})
print(session.run(w))

-9.999977


In [2]:
example_tensor = tf.constant(
[
    [[1.1, 2.2,3.3,4.4],
     [1.1, 2.2,3.3,4.4],
     [1.1, 2.2,3.3,4.4]],
    [[2.1, 2.2,3.3,4.4],
     [2.1, 2.2,3.3,4.4],
     [2.1, 2.2,3.3,4.4]],
])
print(example_tensor)

Tensor("Const:0", shape=(2, 3, 4), dtype=float32)


In [3]:
transposed_tensor = tf.transpose(example_tensor)

In [4]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(example_tensor))

[[[1.1 2.2 3.3 4.4]
  [1.1 2.2 3.3 4.4]
  [1.1 2.2 3.3 4.4]]

 [[2.1 2.2 3.3 4.4]
  [2.1 2.2 3.3 4.4]
  [2.1 2.2 3.3 4.4]]]


In [5]:
print(sess.run(transposed_tensor))

[[[1.1 2.1]
  [1.1 2.1]
  [1.1 2.1]]

 [[2.2 2.2]
  [2.2 2.2]
  [2.2 2.2]]

 [[3.3 3.3]
  [3.3 3.3]
  [3.3 3.3]]

 [[4.4 4.4]
  [4.4 4.4]
  [4.4 4.4]]]


In [6]:
print(transposed_tensor)

Tensor("transpose:0", shape=(4, 3, 2), dtype=float32)


In [7]:
# one way of unroll
a = np.arange(45)
A = np.reshape(a, (1, 5,3,-1))
B = tf.constant(A)

n_C = 5
print(sess.run(B))

[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]
   [24 25 26]]

  [[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]]]


In [10]:
# reshape so that n_C is the rows and the columns are n_H*n_W
with tf.Session() as test:
    print(tf.reshape(B, [n_C, -1]).eval())
    

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]]


In [11]:
print(tf.reshape(B, [n_C, -1]).shape)

(5, 9)
